DROP INDEX IF EXISTS `USER_USERNAME_IDX` ON `USER`;
DROP INDEX IF EXISTS `USER_EMAIL_IDX` ON `USER`;

DROP INDEX IF EXISTS `MESSAGE_SENDER_ID_IDX` ON `MESSAGE`;
DROP INDEX IF EXISTS `MESSAGE_RECEIVER_ID_IDX` ON `MESSAGE`;

DROP INDEX IF EXISTS `DELIVERY_ADDRESS_ID_IDX` ON `DELIVERY`;
DROP INDEX IF EXISTS `DELIVERY_SUPPLIER_ID_IDX` ON `DELIVERY`;
DROP INDEX IF EXISTS `DELIVERY_DELIVERY_DATE_IDX` ON `DELIVERY`;

DROP INDEX IF EXISTS `PRODUCT_IN_STORAGE_BATCH_ID_IDX` ON `PRODUCT_IN_STORAGE`;
DROP INDEX IF EXISTS `PRODUCT_IN_STORAGE_STORAGE_ID_IDX` ON `PRODUCT_IN_STORAGE`;
DROP INDEX IF EXISTS `PRODUCT_IN_STORAGE_QUANTITY_IDX` ON `PRODUCT_IN_STORAGE`;

DROP INDEX IF EXISTS `PRODUCT_ORDER_ORDER_ID_IDX` ON `PRODUCT_ORDER`;
DROP INDEX IF EXISTS `PRODUCT_ORDER_BATCH_ID_IDX` ON `PRODUCT_ORDER`;
DROP INDEX IF EXISTS `PRODUCT_ORDER_QUANTITY_IDX` ON `PRODUCT_ORDER`;

DROP INDEX IF EXISTS `PRODUCT_BATCH_PRODUCT_ID_IDX` ON `PRODUCT_BATCH`;
DROP INDEX IF EXISTS `PRODUCT_BATCH_EAT_BY_DATE_IDX` ON `PRODUCT_BATCH`;

DROP INDEX IF EXISTS `ORDER_PAYMENT_ID_IDX` ON `ORDER`;
DROP INDEX IF EXISTS `ORDER_DELIVERY_ID_IDX` ON `ORDER`;
DROP INDEX IF EXISTS `ORDER_CUSTOMER_ID_IDX` ON `ORDER`;
DROP INDEX IF EXISTS `ORDER_STATE_IDX` ON `ORDER`;

DROP INDEX IF EXISTS `EMPLOYEE_USER_ID_IDX` ON `EMPLOYEE`;

DROP INDEX IF EXISTS `CUSTOMER_USER_ID_IDX` ON `CUSTOMER`;
DROP INDEX IF EXISTS `CUSTOMER_ADDRESS_ID_IDX` ON `CUSTOMER`;

DROP INDEX IF EXISTS `MAKER_ADDRESS_ID_IDX` ON `MAKER`;

DROP INDEX IF EXISTS `STORAGE_ADDRESS_ID_IDX` ON `STORAGE`;
DROP INDEX IF EXISTS `STORAGE_MANAGER_ID_IDX` ON `STORAGE`;

DROP INDEX IF EXISTS `PRODUCT_MAKER_ID_IDX` ON `PRODUCT`;


-- użytkownik login, email,
CREATE UNIQUE INDEX `USER_USERNAME_IDX` ON `foodwarehouse`.`USER` (`USERNAME`);
CREATE UNIQUE INDEX `USER_EMAIL_IDX` ON `foodwarehouse`.`USER` (`E_MAIL`);

-- komunikat, odbiorca, nadawca
CREATE INDEX `MESSAGE_SENDER_ID_IDX` ON `foodwarehouse`.`MESSAGE` (`SENDER_ID`);
CREATE INDEX `MESSAGE_RECEIVER_ID_IDX` ON `foodwarehouse`.`MESSAGE` (`RECEIVER_ID`);

-- dostawa data_dostarczenia
CREATE INDEX `DELIVERY_ADDRESS_ID_IDX` ON `foodwarehouse`.`DELIVERY` (`ADDRESS_ID`);
CREATE INDEX `DELIVERY_SUPPLIER_ID_IDX` ON `foodwarehouse`.`DELIVERY` (`SUPPLIER_ID`);
CREATE INDEX `DELIVERY_DELIVERY_DATE_IDX` ON `foodwarehouse`.`DELIVERY` (`DELIVERY_DATE`);

-- produkt w magazynie - osobne na wszystkie 3
CREATE INDEX `PRODUCT_IN_STORAGE_BATCH_ID_IDX` ON `foodwarehouse`.`PRODUCT_IN_STORAGE` (`BATCH_ID`);
CREATE INDEX `PRODUCT_IN_STORAGE_STORAGE_ID_IDX` ON `foodwarehouse`.`PRODUCT_IN_STORAGE` (`STORAGE_ID`);
CREATE INDEX `PRODUCT_IN_STORAGE_QUANTITY_IDX` ON `foodwarehouse`.`PRODUCT_IN_STORAGE` (`QUANTITY`);

-- produkt w zamówieniu - osobne na wszystkie 3
CREATE INDEX `PRODUCT_ORDER_ORDER_ID_IDX` ON `foodwarehouse`.`PRODUCT_ORDER` (`ORDER_ID`);
CREATE INDEX `PRODUCT_ORDER_BATCH_ID_IDX` ON `foodwarehouse`.`PRODUCT_ORDER` (`BATCH_ID`);
CREATE INDEX `PRODUCT_ORDER_QUANTITY_IDX` ON `foodwarehouse`.`PRODUCT_ORDER` (`QUANTITY`);

-- partia produktu - ko produkt, data_przydatności,
CREATE INDEX `PRODUCT_BATCH_PRODUCT_ID_IDX` ON `foodwarehouse`.`PRODUCT_BATCH` (`PRODUCT_ID`);
CREATE INDEX `PRODUCT_BATCH_EAT_BY_DATE_IDX` ON `foodwarehouse`.`PRODUCT_BATCH` (`EAT_BY_DATE`);

-- zamówienie status
CREATE UNIQUE INDEX `ORDER_PAYMENT_ID_IDX` ON `foodwarehouse`.`ORDER` (`PAYMENT_ID`);
CREATE UNIQUE INDEX `ORDER_DELIVERY_ID_IDX` ON `foodwarehouse`.`ORDER` (`DELIVERY_ID`);
CREATE INDEX `ORDER_CUSTOMER_ID_IDX` ON `foodwarehouse`.`ORDER` (`CUSTOMER_ID`);
CREATE INDEX `ORDER_STATE_IDX` ON `foodwarehouse`.`ORDER` (`ORDER_STATE`);

-- pracownik
CREATE UNIQUE INDEX `EMPLOYEE_USER_ID_IDX` ON `foodwarehouse`.`EMPLOYEE` (`USER_ID`);

-- klient
CREATE UNIQUE INDEX `CUSTOMER_USER_ID_IDX` ON `foodwarehouse`.`CUSTOMER` (`USER_ID`);
CREATE UNIQUE INDEX `CUSTOMER_ADDRESS_ID_IDX` ON `foodwarehouse`.`CUSTOMER` (`ADDRESS_ID`);

-- producent
CREATE UNIQUE INDEX `MAKER_ADDRESS_ID_IDX` ON `foodwarehouse`.`MAKER` (`ADDRESS_ID`);

-- magazyn
CREATE UNIQUE INDEX `STORAGE_ADDRESS_ID_IDX` ON `foodwarehouse`.`STORAGE` (`ADDRESS_ID`);
CREATE INDEX `STORAGE_MANAGER_ID_IDX` ON `foodwarehouse`.`STORAGE` (`MANAGER_ID`);

-- produkt
CREATE INDEX `PRODUCT_MAKER_ID_IDX` ON `foodwarehouse`.`PRODUCT` (`MAKER_ID`);
